model_name: tu-resnest269e
lr: 3.0e-4
n_data: -1
frame_first: 4
frame_last: 4
n_splits: 5
in_ch: 3
image_size: 512
batch_size: 32
max_epochs: 25
warmup_steps_ratio: 0.1
precision: 16
last_single: false
grad_checkpointing: false
decoder_ch_coef: 1
conv3d_kernel_size: 3
segmentor_type: mid-25d
pretrained_model_path: null
pseudo_dir: null
hard_pseudo_label: false
pseudo_frame_aux: false
